### PR TITLE
Renamed app => dapp for naming consistency.

### PR DESCRIPTION
**Pull request by uzyn**

### CODE REVIEW

**Comment by graup** [comment]
What's your motivation for this change? "dapp" would be the whole thing, including the contract, right? While in the "app" directory there is only the code for the "traditional" frontend app (which will hopefully in the future be distributed via Swarm, but currently is usually hosted on some static server).

It's also imaginable to make non-frontend dApps, then the directory could contain some node.js code that a node runs as a background task.

**Comment by uzyn** [comment]
Just wanted to make the naming consistent, is it 'app' or 'dapp' throughout. 

While you do have a point that 'dapp' refers to the whole thing, the same can be said for 'app' too.

Probably the folder should be `ui/` or `frontend/` or `view/`? The `app/` convention of UI probably started with the idea of single-page apps, where it was more traditionally known as views, such as in the the context of MVC (the whole thing is app).

**Comment by graup** [comment]
`view` could be confusing, as depending on which framework you use for your frontend you would have another `view` directory or files inside that.

To backtrack: The whole project is a "[decentralized application](https://github.com/ethereum/wiki/wiki/Ethereum-Development-Tutorial#introduction)" (Đapp).

> [A Đapp is defined as a combination of a contract and a graphical interface for using that contract](https://github.com/ethereum/wiki/wiki/Ethereum-Development-Tutorial#graphical-interfaces-outdated-api)

This would give weight to your `ui` idea. Or more generally, `interface`?

Another idea, what about `client`?

**Comment by uzyn** [comment]
I like `client`, it implies that it is one of the many clients that can be used to access the Dapp.

Thanks for the suggestion.

**Pull request merged**
